config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'login/index'

  resources :posts do
    resources :comments
  end

  authenticated :user do
    root 'posts#index', as: "authenticated_root"
  end

  root 'login#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :post, presence: true
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = current_user.comments.build
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find params[:id]
    unless current_user == @comment.user
      redirect_to(@comment, notice: "You can't edit this comment because you didn't create it.") and return
    end
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment created successfully.' }
        format.json { render :show, status: :created, location: @comment }
        format.js #create.js.erb
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment updated successfully.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    unless current_user == @comment.user
      redirect_to(@comment, notice: "You can't' destroy this comment because you didn't create it.") and return
    else
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to comments_url, notice: 'Comment destroyed successfully.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body)
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find params[:id]
    unless current_user == @post.user
      redirect_to(posts_url, notice: "You can't edit this post because you didn't create it.") and return
     end
  end


  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post created successfully.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post updated successfully.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    unless current_user == @post.user
      redirect_to(posts_url, notice: "You can't destroy this post because you didn't create it.") and return
    else
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post destroyed successfully.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
<p>
  <strong>Posted <%= time_ago_in_words(comment.created_at) %></strong><br />
  <%= h(comment.body) %>
</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
   <% if @comment.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
       <ul>
         <% @comment.errors.full_messages.each do |message| %>
         <li><%= message %></li>
         <% end %>
       </ul>
     </div>
    <% end %>

<div class="field">
  <%= f.label :post_id %><br>
  <%= f.text_field :post_id %>
</div>

<div class="field">
  <%= f.label :body %><br>
  <%= f.text_area :body %>
</div>

<div class="actions">
  <%= f.submit %>
</div>

<% end %>

app/views/comments/create.js.erb
var new_comment = $("<%= escape_javascript(render(:partial => @comment))%>").hide();
$('#comments').prepend(new_comment);
$('#comment_<%= @comment.id %>').fadeIn('slow');
$('#new_comment')[0].reset();

app/views/comments/edit.html.haml
%h1 Editing Comment

  = render 'form'
  = link_to "Show", @comment
  = link_to "Back", comments_path

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.haml
%h1 New Comment

  = render 'form'
  = link_to "Delete", root_path

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.haml
!!!
%html
  %head>
    %title Blog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container
        .navbar-header
          = link_to "Home", root_path, class: "navbar-brand"
        .nav.navbar-nav.navbar-right
          - if user_signed_in?
            = link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-brand"
          - else
            = link_to "Log In", new_user_session_path, class: "navbar-brand"
    .container
      %p.notice= notice
      %p.alert= alert
      = yield

app/views/login/index.html.haml
#banner
  .banner_content
  %h1 Blog
  %button= link_to "Sign Up", new_user_registration_path
  %button= link_to "Log In", new_user_session_path

app/views/posts/_form.html.haml
= simple_form_for(@post, html: {class: 'form-horizontal'}) do |f|
  = f.input :title, label: "Title", input_html: {class: "form-control"}
  = f.input :body, label: "Body", input_html: {class: "form-control"}
  %br/
  = f.button :submit

app/views/posts/edit.html.haml
#edit_post
  %h1 Editing post

  = render 'form'
  %br/
  = link_to "View Post", @post
  |
  = link_to "Home", posts_path

app/views/posts/index.html.haml
#index_posts
  %center
    %h2 My blog posts
    %table
      %thead
        %tr
          %th Title
          %th Body
      %tbody
      - @posts.each do |post|
        %tr
          %td= link_to post.title, post
          %td= post.body
          %td= link_to 'Edit', edit_post_path(post)
          %td= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }
    %br/
    %strong
      = link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New Blog Post

= render 'form'
%br/
= link_to "Back", posts_path

app/views/posts/show.html.haml
- [:notice]
#post
  %h2 Title:
  %h2= @post.title

  %h2 Body:
  %h2= @post.body

  %h3 Comments
  #comments
    = render :partial => @post.comments.reverse
  = simple_form_for([@post, Comment.new], remote: true, html: {class: 'form-horizontal'}) do |f|
    = f.input :body, label: "New Comment", input_html: {class: "form-control"}
    %br/
    = f.button :submit

  %br/
  = link_to 'Edit', edit_post_path(@post)
  |
  = link_to 'Back', posts_path